### ISSUE TITLE
add a Permanently Deactivate Account feature

### ISSUE THREAD

**Issue by rizen** [plainblack/Wing#17]
add it to Wing::Role::DB::Result::User

When an account is disabled it should do the following:

a) be the same as setting the no emails ever flag, not  actually setting it, just overriding it. BTW, I'm not sure if this is a feature of wing or of the individual apps. if it's in the individual apps please move it to wing.

b) do not allow logins

c) do not allow password recovery, instead say this account has been permanently deactivated

d) show as disabled in the admin user search 

e) make it so the user can hit a button to disable their own account. When they do this it should:

e1) Ask them to type their password to confirm with the message: Type your password to PERMANENTLY DEACTIVATE YOUR ACCOUNT.

e2) Log them out.

**Comment by rizen** [comment]
update all 3 apps to make use of it

**Comment by perlDreamer** [comment]
TODO: How to enable Support users (like CeCe) to use this feature.

**Comment by perlDreamer** [comment]
Branch name: user_disable

**Comment by rizen** [comment]
fixed
