### ISSUE TITLE
Chat character limit hard to work with

### ISSUE THREAD

**Issue by perlDreamer** [plainblack/Wing#25]
We should consider lifting/expanding the character limit for chat curators.  It will make it easy for them to copy/paste responses.

**Comment by rizen** [comment]
Give me a use case where more than 255 characters would be beneficial.

**Comment by perlDreamer** [comment]
Here's are 3 examples of something that CC pastes to new people making games:

When designing images for our cards you will want all important information within the blue dotted safe zone. All information between the blue dotted safe zone and the red cut line (this is where we will cut out the item) is not guaranteed to be printed. Everything outside the red cut line is the bleed zone you need the background of your image to fill the bleed zone.

Please note that the estimated ship date offered by our site is simply a guess based on recent production rates, and is subject to change at any time.  We do not offer a guaranteed ship or delivery date.  For more information about the factors that can cause changes in the estimated ship date, you can visit http://help.thegamecrafter.com/article/82-why-has-my-estimated-ship-date-changed

I would recommend that you simply create the game in our system, including the box and the other components. If our system calculates that not all of the parts will fit into the box, you will see a warning message at the upper-right corner of the screen. (You'll also see a box size recommendation on the right-hand side of the Edit Game screen.)

**Comment by rizen** [comment]
I'm going to disagree with increasing the chat size and instead say that these all need to be reworded to be shorter. Way too long of a response for a chat.

**Comment by perlDreamer** [comment]
We use Discord now.
